### ISSUE TITLE
Question about pretrained models

### ISSUE THREAD

**Issue by skyclear** [XLechter/Detail-Preserved-Point-Cloud-Completion-via-SFA#2]
Hello! We try to use pretrained models given on google drive to evaluate the method. It works well on given test data. However, we can only get following results:
![image](https://user-images.githubusercontent.com/32009753/97823028-ae7ca600-1cf2-11eb-81ce-5856b11606c2.png)

I think something may be wrong but we do not change any of the code. Could you help us?

**Comment by XLechter** [comment]
Hi @skyclear,
Some seem meet the same issue but others can run the pre-trained model well.  This is also mentioned in the other issue. #1 
I have not yet figure out the reason for this, but one possible reason is the version of the libs installed by pip.
One solution is you can create a new virtual environment and use the requirements.txt in PCN to install the needed libs and make sure you do not modify the original evaluation file.
I test on tensorflow 1.14 and cuda 9.0 / 10.0 on two computers with no problems, so this may not cause by CUDA version.

**Comment by XLechter** [comment]
This is a result run by others:
![Uploading 96867641-8e054e00-149f-11eb-8104-27035c346aa2.png…]()

**Comment by XLechter** [comment]
This is a result run by others:
![96867641-8e054e00-149f-11eb-8104-27035c346aa2](https://user-images.githubusercontent.com/41005111/98010536-c60e7880-1e31-11eb-8f64-1292894272a4.png)

**Comment by skyclear** [comment]
OK, I'll try it. Thank you very much!

**Comment by XLechter** [comment]
@skyclear also make sure the last parameter in 41 line in eval.py 'model = model_module.Model(inputs, gt, theta, False)' is set to False, this relates to different bn operation in training and testing. And make sure the test.lmdb and test_novel_lmdb not be mistakenly taken. Thank you : )

**Comment by skyclear** [comment]
I test on the same requirements with PCN. On tf1.14, the code will go core dump anyway. The reason may be related with sampling module in tf_ops。 But the code works well on tf1.13 or tf1.15. However, they both get same wrong results like shown upside. I thought it may be related with the precision of devices used. I use 1080ti. Could you tell me what king of device you use? Thank you: )!

**Comment by XLechter** [comment]
Hi @skyclear ,
I use 2080Ti with CUDA 10.0 and tf 1.14.
I am sorry that I cannot tell the exact reason that caused your issue, but I think the device may not be the reason.
By the way, can you train the model? train the model for about 20 epochs will get the similar results in the paper.

**Comment by skyclear** [comment]
Hi @XLechter ,
It will be ok for me to train the model later. Thank you very much for your help!

**Comment by XLechter** [comment]
Currently I close this issue, and I am sorry I cannot recur this bug based on my environment. I check the pretrained model and find the checkpoint is the on the 674000 iterations with batchsize 8 . So you can train the model with this settings and get the similar results.

Someone find the solution to this bug can reopen this issue.
Thank you.

**Comment by Leerw** [comment]
Hi, the link of google drive in  README is 404, could you please send me a copy? lee.rw.cs@gmail.com
Thanks.
